
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - testdb
    environment:
      - ASPNETCORE_URLS=http://+:5000
      
  testdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: testdb
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Luana@2024"
      ACCEPT_EULA: "Y"

